baseURL = 'https://johnmakarov.github.io/victors-blog/'
title = ''
theme = 'my-blog-theme'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = false

[languages.ru]
  contentDir = 'content/ru'
  languageCode = 'ru-ru'
  languageName = 'Русский'
  weight = 1

  [languages.ru.params]
    flag = '🇷🇺'

[languages.en]
  contentDir = 'content/en'
  languageCode = 'en-us'
  languageName = 'English'
  weight = 2

  [languages.en.params]
    flag = '🇬🇧'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false 
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = true
    tabWidth = 4
    